### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-devbox#79]
I launch the installation with `vagrant up > log.txt`
Here the full log: [log.txt](https://github.com/jhipster/jhipster-devbox/files/818340/log.txt)

It need to be analyzed, as there are some errors. Here, 2 of them:
```
ERROR: Unhandled exception
==> default: Traceback (most recent call last):
==> default:   File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
==> default:     function(*args, **kwargs)
==> default:   File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 418, in decompress_and_install_done
==> default:     self.mark_in_config()
==> default:   File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 266, in mark_in_config
==> default:     ConfigHandler().config = config
==> default:   File "/usr/lib/python3/dist-packages/umake/tools.py", line 107, in config
==> default:     with open(config_file, 'w') as f:
==> default: PermissionError: [Errno 13] Permission denied: '/home/vagrant/.config/umake'
==> default: |#############################################################################|
==> default: Downloading and installing requirements
==> default: Installing Visual Studio Code
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
==> default: [ { Error: EACCES: permission denied, mkdir '/home/vagrant/.config/Code'
==> default:       at Error (native)
==> default:     errno: -13,
==> default:     code: 'EACCES',
==> default:     syscall: 'mkdir',
==> default:     path: '/home/vagrant/.config/Code' } ]
```

```
ERROR: Unhandled exception
==> default: Traceback (most recent call last):
==> default:   File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
==> default:     function(*args, **kwargs)
==> default:   File "/usr/lib/python3/dist-packages/umake/frameworks/baseinstaller.py", line 418, in decompress_and_install_done
==> default:     self.mark_in_config()
==> default:   File "/usr/lib/python3/dist-packages/umake/frameworks/__init__.py", line 266, in mark_in_config
==> default:     ConfigHandler().config = config
==> default:   File "/usr/lib/python3/dist-packages/umake/tools.py", line 107, in config
==> default:     with open(config_file, 'w') as f:
==> default: PermissionError: [Errno 13] Permission denied: '/home/vagrant/.config/umake'
```

**Comment by pascalgrimaud** [comment]
Should be easily fixed as soon as we do https://github.com/jhipster/jhipster-devbox/issues/82#issuecomment-284467519 -> so it will be easy to debug
